# Generated by Django 5.2.9 on 2026-04-11 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_source_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('added_by', models.CharField(choices=[('system', 'System'), ('user', 'User')], default='system', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='expenses.category')),
            ],
            options={
                'verbose_name': 'Category Keyword',
                'verbose_name_plural': 'Category Keywords',
                'db_table': 'category_keywords',
                'ordering': ['category__name', 'keyword'],
            },
        ),
        migrations.AddConstraint(
            model_name='categorykeyword',
            constraint=models.UniqueConstraint(fields=('category', 'keyword'), name='unique_category_keyword'),
        ),
        migrations.AddIndex(
            model_name='categorykeyword',
            index=models.Index(fields=['category', 'keyword'], name='category_ke_categor_idx'),
        ),
        migrations.AddIndex(
            model_name='categorykeyword',
            index=models.Index(fields=['keyword'], name='category_ke_keyword_idx'),
        ),
    ]
