# Generated by Django 5.2.9 on 2026-04-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_add_category_keywords'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categorykeyword',
            name='unique_category_keyword',
        ),
        migrations.RenameIndex(
            model_name='categorykeyword',
            new_name='category_ke_categor_34dd17_idx',
            old_name='category_ke_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='categorykeyword',
            new_name='category_ke_keyword_9e010a_idx',
            old_name='category_ke_keyword_idx',
        ),
        migrations.AlterUniqueTogether(
            name='categorykeyword',
            unique_together={('category', 'keyword')},
        ),
    ]
